name: advent_of_code
description: A new Flutter package project.
version: 0.0.1
author: RafaelAudibert
homepage: https://github.com/rafaeelaudibert/AdventOfCode.dart

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"